# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

jobs:
  include:
    - stage: "Deploy"
      name: "pkgdown"
      r: release
      if: |
        repo = rstudio/shinyloadtest AND \
        type = push AND \
        branch =~ /^(master|rc-v\d+\.\d+\.\d+)$/
      before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
      before_deploy:
        - Rscript -e "remotes::install_cran('svglite')"
        - Rscript -e "remotes::install_local()"
        - make prep_vignettes
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
        keep-history: false # overwrite all git history
        on:
          # deploy on any branch as condition is done above
          all_branches: true
