---
title: "Analyzing Load Test Logs"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


There are two types of log files generated while using `shinyloadtest`. The first file is the recording log file. This file is a JSON file that captures all of the HTTP(s) and websocket traffic that occured during the recording. The second type of file is a session log file generated during the load test. A session log file is generated for each simulated session. The two types files are tied together by a set of keys that identify "events" that were recorded and played back in the load test.

> Normally, users will not need to worry about specific files, but should be able to use the tidy data frame for further analysis.


The `shinyloadtest::tidy_loadtest` function uses these files to generate a data frame with load test results. Multiple load tests run against the same recording file can be combined and anayzed at once. The resulting data frame contains the following columns:

Column | Description 
-- | --
run | A label for the load test. A results data frame can include multiple load tests run against the same recording. See `shinyloadtest::tidy_loadtest`
session | An ID for a session within a load test. The ID identifies a "simulated user".
input_line_number | The line number of the event from the recording log file.
event | The type of the event, see the table below.
start | When the event started, relative to the beginning of the load test (seconds).
end |  When the event ended, relative to the beginning of the load test (seconds).
time | The event duration (seconds).
concurrency | How many other simulated users were connected to the application and running events while this event occured.
label | A unique label for the event. This label can be used to compare the event across simulated users or across load tests.

Event Type | Description
-- | -- 
**REQ_HOME** | An event signaling the initial request for the application.
REQ | HTTP requests for static assets used by the app, e.g. javascript or css files.
REQ_TOK / REQ_SINF | HTTP requests internal to shiny that establish a user session.
WS_OPEN | An HTTP request to open a websocket. The websocket layer is used to communicate inputs / outputs.
WS_RECV_INIT | An event signalling the websocket between the client and the app is ready.
**WS_RECV** | This event type represents a user changing an input and receiving an updated output.
PLAYER_SLEEPBEFORE | This event type represents a  user pause, essentially the time a user was looking at the app but not waiting for an updated output. The pause durations come from the recording file.


They key idea is that each row of the data frame represents an event performed by one simulated user. Events include the initial page load, user inputs and their associated outputs, and user wait times. During an analysis, you'll want to compare the duration of event times across different load tests, different users within a load test, or different  concurrency thresholds. 



