---
title: "Load Testing Authenticated Apps"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

`shinyloadtest` supports load testing applications served by [RStudio Connect](https://www.rstudio.com/products/connect/) or [Shiny Server Pro](https://www.rstudio.com/products/connect/) with the following authentication configurations:

* Connect
    * Password
    * LDAP and Active Directory
    * PAM
* Shiny Server Pro
    * Flat-File
    * LDAP and Active Directory
    * PAM

## Recording

`shinyloadtest::record_session` will automatically detect when an application is protected using a supported authentication scheme and will prompt for a username and password.

If `record_session` is called from within an RStudio IDE session, two UI dialogs will appear. If it's called from an R session in a command-line setting, prompts will appear on standard output.

The supplied username and password are used for the duration of the recording to interact with the application, but these credentials are not stored in the recording file.

## Load testing

Because credentials are not stored in recordings, a username and password must be supplied to `shinycannon` in order to load test authenticated applications.

`shinycannon` does not have `--user` and `--password` arguments for security reasons, so that these strings will not appear in a process list. Instead, `SHINYCANNON_USER` and `SHINYCANNON_PASS` environment variables must be set.

On Linux and macOS, `shinycannon` can be run with these variables set like this:

```
$ export SHINYCANNON_USER=myUser
$ export SHINYCANNON_PASS=myPass
$ shinycannon recording.log https://shinyapp.example.com/ --workers 5 --loaded-duration-minutes 2 --output-dir run1
```
