on:
  push:
    branches: [main, rc-**]
  pull_request:
    branches: [main]
  schedule:
    - cron:  '0 9 * * 0' # every sunday

name: Package Checks

jobs:
  pkgdown:
    uses: rstudio/shinycoreci/.github/workflows/call-pkgdown.yaml@v1
  rituals:
    uses: rstudio/shinycoreci/.github/workflows/call-rituals.yaml@v1
  R-CMD-check:
    uses: rstudio/shinycoreci/.github/workflows/call-R-CMD-check.yaml@v1
    with:
      run-dont-test: true
